# This contains all the site specific information (outside of database.yml) that should not be checked into version control.
# It is read in by environment.rb.

#
# It must contain the following fields:
#

##########################
### EMAIL
##########################

admin:
  email: vicky@performantsoftware.com

# For getting automatic emails when an error occurs
# exception_recipients: List of all emails that should receive the notification
# sender_address: Who the notification email will be from
# email_prefix: What each email should be prefixed with
exception_notifier:
  exception_recipients: [ "first@example.com", "second@example.com" ]
  sender_address: '"Application Error" <admin@example.com>'
  email_prefix: "[Project] "

# For setting up email - this example uses gmail
smtp_settings:
  address: "smtp.gmail.com"
  port: 587
  user_name: 'admin@example.com'
  password: 'super-secret'
  authentication: :plain
  return_path: http://example.com

project_manager_email: 'manager example com'

##########################
### SOLR
##########################

# Where the solr index has been set up
solr:
  url: "http://localhost:8983/solr"
  core_prefix: "localhost:8983/solr"
  path: "/fullpath/solr_3.1"
