# This contains all the site specific information (outside of database.yml) that should not be checked into version control.
# It is read in by environment.rb.

#
# It must contain the following fields:
#
defaults: &defaults

  ##########################
  ### SKIN
  ##########################

  site_name_title: 'Arc Catalog'

  ##########################
  ### SYSTEM
  ##########################

  # this is the path where the "identify" program is located.
  paperclip:
    image_magic_path: '/usr/bin'

  ##########################
  ### EMAIL
  ##########################

  admin:
    email: vicky@performantsoftware.com

  # For getting automatic emails when an error occurs
  # exception_recipients: List of all emails that should receive the notification
  # sender_address: Who the notification email will be from
  # email_prefix: What each email should be prefixed with
  exception_notifier:
    exception_recipients: [ "root@localhost" ]
    sender_address: '"Arc Catalog" <arc@localhost>'
    email_prefix: "[Project] "

  # For setting up email - this example uses gmail
  smtp_settings:
    address: "smtp.gmail.com"
    port: 587
    user_name: 'admin@example.com'
    password: 'super-secret'
    authentication: :plain
    return_path: http://example.com
    enable_starttls_auto: true
    xsmtpapi: 'catalog'
    domain: 'catalog.ar-c.org'

  project_manager_email: 'manager example com'

  ##########################
  ### SOLR
  ##########################

  # Where the solr index has been set up
  solr:
    url: "http://localhost:8983/solr"
    core_prefix: "localhost:8983/solr"
    path: "~/solr"

  folders:
    rdf: "~/rdf"
    marc: "~/marc"
    ecco: "~/ecco"
    rdf_indexer: "~/rdf-indexer"
    backups: "~/backups"
    uploaded_data: "~/uploaded_data"
    tasks_send_method: "scp"
    tamu_key: 'private-token'

  production:
    ssh_user: "nines"
    ssh_host: "arc.performantsoftware.com"

  ##########################
  ### CAPISTRANO
  ##########################

  capistrano:
    edge:
      user: 'arc'
      ssh_name: 'ssh-name-to-login-to-server'
      ruby: 'ruby-1.9.3-p374@catalog'
      system_rvm: false
      deploy_base: '/home/arc/www'
    prod:
      user: 'arc'
      ssh_name: 'ssh-name-to-login-to-server'
      ruby: 'ruby-1.9.3-p374@catalog'
      system_rvm: false
      deploy_base: '/home/arc/www'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
