# This contains all the site specific information (outside of database.yml) that should not be checked into version control.
# It is read in by environment.rb.

#
# It must contain the following fields:
#

##########################
### SKIN
##########################

site_name_title: 'Arc Catalog'

##########################
### SYSTEM
##########################

# this is the path where the "identify" program is located.
paperclip:
  image_magic_path: '/opt/local/bin'

##########################
### EMAIL
##########################

admin:
  email: vicky@performantsoftware.com

# For getting automatic emails when an error occurs
# exception_recipients: List of all emails that should receive the notification
# sender_address: Who the notification email will be from
# email_prefix: What each email should be prefixed with
exception_notifier:
  exception_recipients: [ "first@example.com", "second@example.com" ]
  sender_address: '"Application Error" <admin@example.com>'
  email_prefix: "[Project] "

# For setting up email - this example uses gmail
smtp_settings:
  address: "smtp.gmail.com"
  port: 587
  user_name: 'admin@example.com'
  password: 'super-secret'
  authentication: :plain
  return_path: http://example.com

project_manager_email: 'manager example com'

##########################
### SOLR
##########################

# Where the solr index has been set up
solr:
  url: "http://localhost:8983/solr"
  core_prefix: "localhost:8983/solr"
  path: "/fullpath/solr"

folders:
  rdf: "/path/rdf"
  marc: "/path/marc"
  ecco: "/path/ecco"
  rdf_indexer: "/path/to/source/of/rdf-indexer"
  tamu_key: 'private-token'

production:
  ssh: "nines@arc.performantsoftware.com"

##########################
### CAPISTRANO
##########################

capistrano:
  edge_tamu:
    user: 'user-name-to-login-to-server'
    ssh_name: 'ssh-name-to-login-to-server'
    ruby: 'ruby-1.9.3-p374'
    system_rvm: true
    deploy_base: '/full/path/to/folder/that/all/web/apps/are/deployed/to'

  edge_rack:
    user: 'user-name-to-login-to-server'
    ssh_name: 'ssh-name-to-login-to-server'
    ruby: 'ruby-1.9.3-p0'
    system_rvm: false
    deploy_base: '/full/path/to/folder/that/all/web/apps/are/deployed/to'
